name = "BioMakie"
uuid = "7de43156-b762-4475-b39f-ba1e1e59ee2f"
authors = ["Daniel Kool"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MIToS = "51bafb47-8a16-5ded-8b04-24ef4eede0b5"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieLayout = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
AbstractPlotting = "0.11, 0.12"
BioSequences = "2.0"
BioStructures = "0.11"
CairoMakie = "0.3"
ColorSchemes = "3.9.0"
Colors = "0.12.3"
DataStructures = "0.17, 0.18"
Distances = "0.9"
FileIO = "1.4"
GLFW = "3.2"
GLMakie = "0.1"
GeometryBasics = "0.2"
JLD2 = "0.1"
JSServe = "0.6"
Lazy = "0.15"
MIToS = "2.4"
MacroTools = "0.5"
Makie = "0.11"
MakieLayout = "0.9.9"
Parameters = "0.12"
RecursiveArrayTools = "2.5"
SplitApplyCombine = "1.1.1"
TableTraitsUtils = "1.0"
TensorCast = "0.3"
WGLMakie = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
