name = "BioMakie"
uuid = "7de43156-b762-4475-b39f-ba1e1e59ee2f"
authors = ["Daniel Kool"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CommonSubexpressions = "bbf7d656-a473-5ed7-a52c-81e309532950"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FastaIO = "a0c94c4b-ebed-5953-b5fc-82fe598ac79f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MIToS = "51bafb47-8a16-5ded-8b04-24ef4eede0b5"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PairwiseListMatrices = "f9da4da7-9382-5435-b973-175f5d8dfb32"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
GLFW = "3.4"
Literate = "2.8"
GeometryBasics = "0.3"
BioSequences = "2.0"
Colors = "0.12"
DrWatson = "1.18"
PairwiseListMatrices = "0.8"
DataStructures = "0.18"
WGLMakie = "0.3"
CommonSubexpressions = "0.3"
TensorCast = "0.3"
TableTraitsUtils = "1.0"
Parameters = "0.12"
CUDA = "2.6"
Distributions = "0.24"
BioStructures = "0.11"
FileIO = "1.4"
JSServe = "1.2"
AbstractPlotting = "0.15"
Observables = "0.3"
FastaIO = "1.0"
SplitApplyCombine = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
