name = "BioMakie"
uuid = "7de43156-b762-4475-b39f-ba1e1e59ee2f"
authors = ["Daniel Kool"]
version = "0.2.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CommonSubexpressions = "bbf7d656-a473-5ed7-a52c-81e309532950"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FastaIO = "a0c94c4b-ebed-5953-b5fc-82fe598ac79f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MIToS = "51bafb47-8a16-5ded-8b04-24ef4eede0b5"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Phylo = "aea672f4-3940-5932-aa44-993d1c3ff149"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"

[compat]
BioSequences = "2.0"
BioStructures = "0.11"
CUDA = "2.4, 3.0"
ColorSchemes = "3.10"
Colors = "0.12"
CommonSubexpressions = "0.3"
DataFrames = "0.22"
DataStructures = "0.17, 0.18"
Distances = "0.10"
Distributions = "0.24"
Documenter = "0.26"
FastaIO = "1.0"
FileIO = "1.4"
GLFW = "3.4"
GeometryBasics = "0.3"
Hyperscript = "0.0.4"
JSServe = "1.2"
LightGraphs = "1.3"
Literate = "2.8"
MIToS = "2.5"
Observables = "0.3, 0.4"
OrderedCollections = "1.4"
Parameters = "0.12"
Phylo = "0.4"
SplitApplyCombine = "1.1"
TableTraitsUtils = "1.0"
TensorCast = "0.3, 0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
